[build]
command = "ng build"
CI="ng build"
commandOrigin: "ui"
publish = "/opt/build/repo/dist/furntiture-project/browser"
publishOrigin: "ui"

[functions]
  node_bundler = "esbuild"
  functionsDirectory: "/opt/build/repo/netlify/functions"

[plugins]  
 package: '@netlify/angular-runtime'
